Add pre-push sanity checks

diff --git a/scripts/sanity/git-hooks/pre-commit b/scripts/sanity/git-hooks/pre-commit
--- a/scripts/sanity/git-hooks/pre-commit
+++ b/scripts/sanity/git-hooks/pre-commit
@@ -5,9 +5,9 @@ echo "Running style analysis..."
 status=$?
 
 if [ "$status" = 0 ] ; then
-    echo "Static analysis found no problems."
+    echo "Style analysis found no problems."
     exit 0
 else
-    echo 1>&2 "Static analysis found violations it could not fix."
+    echo 1>&2 "Style analysis found violations it could not fix."
     exit 1
 fi
